<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\JadwalPelajaran;
use App\Models\Semester;

class JadwalPelajaranSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $jadwals = [
            // kelas 1
            [
                'jam_ke' => 1,
                'id_kelas' => 1,
                'id_mapel' => 1,
                'id_guru' => 2,
                'hari' => 'Senin',
                'jam_mulai' => '07.00',
                'jam_selesai' => '08.00',
            ],
            [
                'jam_ke' => 2,
                'id_kelas' => 1,
                'id_mapel' => 2,
                'id_guru' => 3,
                'hari' => 'Senin',
                'jam_mulai' => '08.00',
                'jam_selesai' => '09.00',
            ],
            [
                'jam_ke' => 3,
                'id_kelas' => 1,
                'id_mapel' => 3,
                'id_guru' => 4,
                'hari' => 'Senin',
                'jam_mulai' => '09.00',
                'jam_selesai' => '10.00',
            ],
            [
                'jam_ke' => 4,
                'id_kelas' => 1,
                'id_mapel' => 4,
                'id_guru' => 5,
                'hari' => 'Senin',
                'jam_mulai' => '11.00',
                'jam_selesai' => '12.00',
            ],
            [
                'jam_ke' => 5,
                'id_kelas' => 1,
                'id_mapel' => 5,
                'id_guru' => 6,
                'hari' => 'Senin',
                'jam_mulai' => '12.00',
                'jam_selesai' => '13.00',
            ],
            [
                'jam_ke' => 6,
                'id_kelas' => 1,
                'id_mapel' => 6,
                'id_guru' => 7,
                'hari' => 'Senin',
                'jam_mulai' => '13.00',
                'jam_selesai' => '14.00',
            ],
            [
                'jam_ke' => 7,
                'id_kelas' => 1,
                'id_mapel' => 7,
                'id_guru' => 8,
                'hari' => 'Senin',
                'jam_mulai' => '14.00',
                'jam_selesai' => '15.00',
            ],
            [
                'jam_ke' => 8,
                'id_kelas' => 1,
                'id_mapel' => 8,
                'id_guru' => 9,
                'hari' => 'Senin',
                'jam_mulai' => '15.00',
                'jam_selesai' => '16.00',
            ],
            [
                'jam_ke' => 1,
                'id_kelas' => 1,
                'id_mapel' => 9,
                'id_guru' => 10,
                'hari' => 'Selasa',
                'jam_mulai' => '07.00',
                'jam_selesai' => '08.00',
            ],
            [
                'jam_ke' => 2,
                'id_kelas' => 1,
                'id_mapel' => 9,
                'id_guru' => 11,
                'hari' => 'Selasa',
                'jam_mulai' => '08.00',
                'jam_selesai' => '09.00',
            ],
            [
                'jam_ke' => 3,
                'id_kelas' => 1,
                'id_mapel' => 10,
                'id_guru' => 11,
                'hari' => 'Selasa',
                'jam_mulai' => '09.00',
                'jam_selesai' => '10.00',
            ],
            [
                'jam_ke' => 4,
                'id_kelas' => 1,
                'id_mapel' => 11,
                'id_guru' => 12,
                'hari' => 'Selasa',
                'jam_mulai' => '10.00',
                'jam_selesai' => '11.00',
            ],
            [
                'jam_ke' => 5,
                'id_kelas' => 1,
                'id_mapel' => 12,
                'id_guru' => 13,
                'hari' => 'Selasa',
                'jam_mulai' => '11.00',
                'jam_selesai' => '12.00',
            ],
            [
                'jam_ke' => 6,
                'id_kelas' => 1,
                'id_mapel' => 13,
                'id_guru' => 14,
                'hari' => 'Selasa',
                'jam_mulai' => '12.00',
                'jam_selesai' => '13.00',
            ],
            [
                'jam_ke' => 7,
                'id_kelas' => 1,
                'id_mapel' => 14,
                'id_guru' => 15,
                'hari' => 'Selasa',
                'jam_mulai' => '13.00',
                'jam_selesai' => '14.00',
            ],
            [
                'jam_ke' => 8,
                'id_kelas' => 1,
                'id_mapel' => 15,
                'id_guru' => 16,
                'hari' => 'Selasa',
                'jam_mulai' => '14.00',
                'jam_selesai' => '15.00',
            ],
            [
                'jam_ke' => 1,
                'id_kelas' => 1,
                'id_mapel' => 16,
                'id_guru' => 17,
                'hari' => 'Rabu',
                'jam_mulai' => '07.00',
                'jam_selesai' => '08.00',
            ],
            [
                'jam_ke' => 2,
                'id_kelas' => 1,
                'id_mapel' => 17,
                'id_guru' => 18,
                'hari' => 'Rabu',
                'jam_mulai' => '08.00',
                'jam_selesai' => '09.00',
            ],
            [
                'jam_ke' => 3,
                'id_kelas' => 1,
                'id_mapel' => 18,
                'id_guru' => 19,
                'hari' => 'Rabu',
                'jam_mulai' => '09.00',
                'jam_selesai' => '10.00',
            ],
            [
                'jam_ke' => 4,
                'id_kelas' => 1,
                'id_mapel' => 19,
                'id_guru' => 20,
                'hari' => 'Rabu',
                'jam_mulai' => '10.00',
                'jam_selesai' => '11.00',
            ],
            [
                'jam_ke' => 5,
                'id_kelas' => 1,
                'id_mapel' => 2,
                'id_guru' => 1,
                'hari' => 'Rabu',
                'jam_mulai' => '11.00',
                'jam_selesai' => '12.00',
            ],
            [
                'jam_ke' => 6,
                'id_kelas' => 1,
                'id_mapel' => 3,
                'id_guru' => 2,
                'hari' => 'Rabu',
                'jam_mulai' => '12.00',
                'jam_selesai' => '13.00',
            ],
            [
                'jam_ke' => 7,
                'id_kelas' => 1,
                'id_mapel' => 4,
                'id_guru' => 3,
                'hari' => 'Rabu',
                'jam_mulai' => '13.00',
                'jam_selesai' => '14.00',
            ],
            [
                'jam_ke' => 8,
                'id_kelas' => 1,
                'id_mapel' => 5,
                'id_guru' => 4,
                'hari' => 'Rabu',
                'jam_mulai' => '14.00',
                'jam_selesai' => '15.00',
            ],
            [
                'jam_ke' => 1,
                'id_kelas' => 1,
                'id_mapel' => 6,
                'id_guru' => 5,
                'hari' => 'Kamis',
                'jam_mulai' => '07.00',
                'jam_selesai' => '08.00',
            ],
            [
                'jam_ke' => 2,
                'id_kelas' => 1,
                'id_mapel' => 7,
                'id_guru' => 6,
                'hari' => 'Kamis',
                'jam_mulai' => '08.00',
                'jam_selesai' => '09.00',
            ],
            [
                'jam_ke' => 3,
                'id_kelas' => 1,
                'id_mapel' => 8,
                'id_guru' => 7,
                'hari' => 'Kamis',
                'jam_mulai' => '09.00',
                'jam_selesai' => '10.00',
            ],
            [
                'jam_ke' => 4,
                'id_kelas' => 1,
                'id_mapel' => 9,
                'id_guru' => 8,
                'hari' => 'Kamis',
                'jam_mulai' => '10.00',
                'jam_selesai' => '11.00',
            ],
            [
                'jam_ke' => 5,
                'id_kelas' => 1,
                'id_mapel' => 10,
                'id_guru' => 9,
                'hari' => 'Kamis',
                'jam_mulai' => '11.00',
                'jam_selesai' => '12.00',
            ],
            [
                'jam_ke' => 6,
                'id_kelas' => 1,
                'id_mapel' => 11,
                'id_guru' => 10,
                'hari' => 'Kamis',
                'jam_mulai' => '12.00',
                'jam_selesai' => '13.00',
            ],
            [
                'jam_ke' => 7,
                'id_kelas' => 1,
                'id_mapel' => 12,
                'id_guru' => 11,
                'hari' => 'Kamis',
                'jam_mulai' => '13.00',
                'jam_selesai' => '14.00',
            ],
            [
                'jam_ke' => 8,
                'id_kelas' => 1,
                'id_mapel' => 13,
                'id_guru' => 12,
                'hari' => 'Kamis',
                'jam_mulai' => '14.00',
                'jam_selesai' => '15.00',
            ],
            [
                'jam_ke' => 1,
                'id_kelas' => 1,
                'id_mapel' => 14,
                'id_guru' => 13,
                'hari' => 'Jumat',
                'jam_mulai' => '07.00',
                'jam_selesai' => '08.00',
            ],
            [
                'jam_ke' => 2,
                'id_kelas' => 1,
                'id_mapel' => 15,
                'id_guru' => 14,
                'hari' => 'Jumat',
                'jam_mulai' => '08.00',
                'jam_selesai' => '09.00',
            ],
            [
                'jam_ke' => 3,
                'id_kelas' => 1,
                'id_mapel' => 16,
                'id_guru' => 15,
                'hari' => 'Jumat',
                'jam_mulai' => '09.00',
                'jam_selesai' => '10.00',
            ],
            [
                'jam_ke' => 4,
                'id_kelas' => 1,
                'id_mapel' => 17,
                'id_guru' => 16,
                'hari' => 'Jumat',
                'jam_mulai' => '10.00',
                'jam_selesai' => '11.00',
            ],
            [
                'jam_ke' => 5,
                'id_kelas' => 1,
                'id_mapel' => 18,
                'id_guru' => 17,
                'hari' => 'Jumat',
                'jam_mulai' => '11.00',
                'jam_selesai' => '12.00',
            ],
            [
                'jam_ke' => 6,
                'id_kelas' => 1,
                'id_mapel' => 19,
                'id_guru' => 18,
                'hari' => 'Jumat',
                'jam_mulai' => '12.00',
                'jam_selesai' => '13.00',
            ],
            [
                'jam_ke' => 7,
                'id_kelas' => 1,
                'id_mapel' => 1,
                'id_guru' => 2,
                'hari' => 'Jumat',
                'jam_mulai' => '13.00',
                'jam_selesai' => '14.00',
            ],
            [
                'jam_ke' => 8,
                'id_kelas' => 1,
                'id_mapel' => 2,
                'id_guru' => 3,
                'hari' => 'Jumat',
                'jam_mulai' => '14.00',
                'jam_selesai' => '15.00',
            ],

            //kelas 2

            [
                'jam_ke' => 1,
                'id_kelas' => 2,
                'id_mapel' => 1,
                'id_guru' => 2,
                'hari' => 'Senin',
                'jam_mulai' => '07.00',
                'jam_selesai' => '08.00',
            ],
            [
                'jam_ke' => 2,
                'id_kelas' => 2,
                'id_mapel' => 2,
                'id_guru' => 3,
                'hari' => 'Senin',
                'jam_mulai' => '08.00',
                'jam_selesai' => '09.00',
            ],
            [
                'jam_ke' => 3,
                'id_kelas' => 2,
                'id_mapel' => 3,
                'id_guru' => 4,
                'hari' => 'Senin',
                'jam_mulai' => '09.00',
                'jam_selesai' => '10.00',
            ],
            [
                'jam_ke' => 4,
                'id_kelas' => 2,
                'id_mapel' => 4,
                'id_guru' => 5,
                'hari' => 'Senin',
                'jam_mulai' => '11.00',
                'jam_selesai' => '12.00',
            ],
            [
                'jam_ke' => 5,
                'id_kelas' => 2,
                'id_mapel' => 5,
                'id_guru' => 6,
                'hari' => 'Senin',
                'jam_mulai' => '12.00',
                'jam_selesai' => '13.00',
            ],
            [
                'jam_ke' => 6,
                'id_kelas' => 2,
                'id_mapel' => 6,
                'id_guru' => 7,
                'hari' => 'Senin',
                'jam_mulai' => '13.00',
                'jam_selesai' => '14.00',
            ],
            [
                'jam_ke' => 7,
                'id_kelas' => 2,
                'id_mapel' => 7,
                'id_guru' => 8,
                'hari' => 'Senin',
                'jam_mulai' => '14.00',
                'jam_selesai' => '15.00',
            ],
            [
                'jam_ke' => 8,
                'id_kelas' => 2,
                'id_mapel' => 8,
                'id_guru' => 9,
                'hari' => 'Senin',
                'jam_mulai' => '15.00',
                'jam_selesai' => '16.00',
            ],
            [
                'jam_ke' => 1,
                'id_kelas' => 2,
                'id_mapel' => 9,
                'id_guru' => 10,
                'hari' => 'Selasa',
                'jam_mulai' => '07.00',
                'jam_selesai' => '08.00',
            ],
            [
                'jam_ke' => 2,
                'id_kelas' => 2,
                'id_mapel' => 9,
                'id_guru' => 11,
                'hari' => 'Selasa',
                'jam_mulai' => '08.00',
                'jam_selesai' => '09.00',
            ],
            [
                'jam_ke' => 3,
                'id_kelas' => 2,
                'id_mapel' => 10,
                'id_guru' => 11,
                'hari' => 'Selasa',
                'jam_mulai' => '09.00',
                'jam_selesai' => '10.00',
            ],
            [
                'jam_ke' => 4,
                'id_kelas' => 2,
                'id_mapel' => 11,
                'id_guru' => 12,
                'hari' => 'Selasa',
                'jam_mulai' => '10.00',
                'jam_selesai' => '11.00',
            ],
            [
                'jam_ke' => 5,
                'id_kelas' => 2,
                'id_mapel' => 12,
                'id_guru' => 13,
                'hari' => 'Selasa',
                'jam_mulai' => '11.00',
                'jam_selesai' => '12.00',
            ],
            [
                'jam_ke' => 6,
                'id_kelas' => 2,
                'id_mapel' => 13,
                'id_guru' => 14,
                'hari' => 'Selasa',
                'jam_mulai' => '12.00',
                'jam_selesai' => '13.00',
            ],
            [
                'jam_ke' => 7,
                'id_kelas' => 2,
                'id_mapel' => 14,
                'id_guru' => 15,
                'hari' => 'Selasa',
                'jam_mulai' => '13.00',
                'jam_selesai' => '14.00',
            ],
            [
                'jam_ke' => 8,
                'id_kelas' => 2,
                'id_mapel' => 15,
                'id_guru' => 16,
                'hari' => 'Selasa',
                'jam_mulai' => '14.00',
                'jam_selesai' => '15.00',
            ],
            [
                'jam_ke' => 1,
                'id_kelas' => 2,
                'id_mapel' => 16,
                'id_guru' => 17,
                'hari' => 'Rabu',
                'jam_mulai' => '07.00',
                'jam_selesai' => '08.00',
            ],
            [
                'jam_ke' => 2,
                'id_kelas' => 2,
                'id_mapel' => 17,
                'id_guru' => 18,
                'hari' => 'Rabu',
                'jam_mulai' => '08.00',
                'jam_selesai' => '09.00',
            ],
            [
                'jam_ke' => 3,
                'id_kelas' => 2,
                'id_mapel' => 18,
                'id_guru' => 19,
                'hari' => 'Rabu',
                'jam_mulai' => '09.00',
                'jam_selesai' => '10.00',
            ],
            [
                'jam_ke' => 4,
                'id_kelas' => 2,
                'id_mapel' => 19,
                'id_guru' => 20,
                'hari' => 'Rabu',
                'jam_mulai' => '10.00',
                'jam_selesai' => '11.00',
            ],
            [
                'jam_ke' => 5,
                'id_kelas' => 2,
                'id_mapel' => 2,
                'id_guru' => 1,
                'hari' => 'Rabu',
                'jam_mulai' => '11.00',
                'jam_selesai' => '12.00',
            ],
            [
                'jam_ke' => 6,
                'id_kelas' => 2,
                'id_mapel' => 3,
                'id_guru' => 2,
                'hari' => 'Rabu',
                'jam_mulai' => '12.00',
                'jam_selesai' => '13.00',
            ],
            [
                'jam_ke' => 7,
                'id_kelas' => 2,
                'id_mapel' => 4,
                'id_guru' => 3,
                'hari' => 'Rabu',
                'jam_mulai' => '13.00',
                'jam_selesai' => '14.00',
            ],
            [
                'jam_ke' => 8,
                'id_kelas' => 2,
                'id_mapel' => 5,
                'id_guru' => 4,
                'hari' => 'Rabu',
                'jam_mulai' => '14.00',
                'jam_selesai' => '15.00',
            ],
            [
                'jam_ke' => 1,
                'id_kelas' => 2,
                'id_mapel' => 6,
                'id_guru' => 5,
                'hari' => 'Kamis',
                'jam_mulai' => '07.00',
                'jam_selesai' => '08.00',
            ],
            [
                'jam_ke' => 2,
                'id_kelas' => 2,
                'id_mapel' => 7,
                'id_guru' => 6,
                'hari' => 'Kamis',
                'jam_mulai' => '08.00',
                'jam_selesai' => '09.00',
            ],
            [
                'jam_ke' => 3,
                'id_kelas' => 2,
                'id_mapel' => 8,
                'id_guru' => 7,
                'hari' => 'Kamis',
                'jam_mulai' => '09.00',
                'jam_selesai' => '10.00',
            ],
            [
                'jam_ke' => 4,
                'id_kelas' => 2,
                'id_mapel' => 9,
                'id_guru' => 8,
                'hari' => 'Kamis',
                'jam_mulai' => '10.00',
                'jam_selesai' => '11.00',
            ],
            [
                'jam_ke' => 5,
                'id_kelas' => 2,
                'id_mapel' => 10,
                'id_guru' => 9,
                'hari' => 'Kamis',
                'jam_mulai' => '11.00',
                'jam_selesai' => '12.00',
            ],
            [
                'jam_ke' => 6,
                'id_kelas' => 2,
                'id_mapel' => 11,
                'id_guru' => 10,
                'hari' => 'Kamis',
                'jam_mulai' => '12.00',
                'jam_selesai' => '13.00',
            ],
            [
                'jam_ke' => 7,
                'id_kelas' => 2,
                'id_mapel' => 12,
                'id_guru' => 11,
                'hari' => 'Kamis',
                'jam_mulai' => '13.00',
                'jam_selesai' => '14.00',
            ],
            [
                'jam_ke' => 8,
                'id_kelas' => 2,
                'id_mapel' => 13,
                'id_guru' => 12,
                'hari' => 'Kamis',
                'jam_mulai' => '14.00',
                'jam_selesai' => '15.00',
            ],
            [
                'jam_ke' => 1,
                'id_kelas' => 2,
                'id_mapel' => 14,
                'id_guru' => 13,
                'hari' => 'Jumat',
                'jam_mulai' => '07.00',
                'jam_selesai' => '08.00',
            ],
            [
                'jam_ke' => 2,
                'id_kelas' => 2,
                'id_mapel' => 15,
                'id_guru' => 14,
                'hari' => 'Jumat',
                'jam_mulai' => '08.00',
                'jam_selesai' => '09.00',
            ],
            [
                'jam_ke' => 3,
                'id_kelas' => 2,
                'id_mapel' => 16,
                'id_guru' => 15,
                'hari' => 'Jumat',
                'jam_mulai' => '09.00',
                'jam_selesai' => '10.00',
            ],
            [
                'jam_ke' => 4,
                'id_kelas' => 2,
                'id_mapel' => 17,
                'id_guru' => 16,
                'hari' => 'Jumat',
                'jam_mulai' => '10.00',
                'jam_selesai' => '11.00',
            ],
            [
                'jam_ke' => 5,
                'id_kelas' => 2,
                'id_mapel' => 18,
                'id_guru' => 17,
                'hari' => 'Jumat',
                'jam_mulai' => '11.00',
                'jam_selesai' => '12.00',
            ],
            [
                'jam_ke' => 6,
                'id_kelas' => 2,
                'id_mapel' => 19,
                'id_guru' => 18,
                'hari' => 'Jumat',
                'jam_mulai' => '12.00',
                'jam_selesai' => '13.00',
            ],
            [
                'jam_ke' => 7,
                'id_kelas' => 2,
                'id_mapel' => 1,
                'id_guru' => 2,
                'hari' => 'Jumat',
                'jam_mulai' => '13.00',
                'jam_selesai' => '14.00',
            ],
            [
                'jam_ke' => 8,
                'id_kelas' => 2,
                'id_mapel' => 2,
                'id_guru' => 3,
                'hari' => 'Jumat',
                'jam_mulai' => '14.00',
                'jam_selesai' => '15.00',
            ],

            // kelas 3

            [
                'jam_ke' => 1,
                'id_kelas' => 3,
                'id_mapel' => 1,
                'id_guru' => 2,
                'hari' => 'Senin',
                'jam_mulai' => '07.00',
                'jam_selesai' => '08.00',
            ],
            [
                'jam_ke' => 2,
                'id_kelas' => 3,
                'id_mapel' => 2,
                'id_guru' => 3,
                'hari' => 'Senin',
                'jam_mulai' => '08.00',
                'jam_selesai' => '09.00',
            ],
            [
                'jam_ke' => 3,
                'id_kelas' => 3,
                'id_mapel' => 3,
                'id_guru' => 4,
                'hari' => 'Senin',
                'jam_mulai' => '09.00',
                'jam_selesai' => '10.00',
            ],
            [
                'jam_ke' => 4,
                'id_kelas' => 3,
                'id_mapel' => 4,
                'id_guru' => 5,
                'hari' => 'Senin',
                'jam_mulai' => '11.00',
                'jam_selesai' => '12.00',
            ],
            [
                'jam_ke' => 5,
                'id_kelas' => 3,
                'id_mapel' => 5,
                'id_guru' => 6,
                'hari' => 'Senin',
                'jam_mulai' => '12.00',
                'jam_selesai' => '13.00',
            ],
            [
                'jam_ke' => 6,
                'id_kelas' => 3,
                'id_mapel' => 6,
                'id_guru' => 7,
                'hari' => 'Senin',
                'jam_mulai' => '13.00',
                'jam_selesai' => '14.00',
            ],
            [
                'jam_ke' => 7,
                'id_kelas' => 3,
                'id_mapel' => 7,
                'id_guru' => 8,
                'hari' => 'Senin',
                'jam_mulai' => '14.00',
                'jam_selesai' => '15.00',
            ],
            [
                'jam_ke' => 8,
                'id_kelas' => 3,
                'id_mapel' => 8,
                'id_guru' => 9,
                'hari' => 'Senin',
                'jam_mulai' => '15.00',
                'jam_selesai' => '16.00',
            ],
            [
                'jam_ke' => 1,
                'id_kelas' => 3,
                'id_mapel' => 9,
                'id_guru' => 10,
                'hari' => 'Selasa',
                'jam_mulai' => '07.00',
                'jam_selesai' => '08.00',
            ],
            [
                'jam_ke' => 2,
                'id_kelas' => 3,
                'id_mapel' => 9,
                'id_guru' => 11,
                'hari' => 'Selasa',
                'jam_mulai' => '08.00',
                'jam_selesai' => '09.00',
            ],
            [
                'jam_ke' => 3,
                'id_kelas' => 3,
                'id_mapel' => 10,
                'id_guru' => 11,
                'hari' => 'Selasa',
                'jam_mulai' => '09.00',
                'jam_selesai' => '10.00',
            ],
            [
                'jam_ke' => 4,
                'id_kelas' => 3,
                'id_mapel' => 11,
                'id_guru' => 12,
                'hari' => 'Selasa',
                'jam_mulai' => '10.00',
                'jam_selesai' => '11.00',
            ],
            [
                'jam_ke' => 5,
                'id_kelas' => 3,
                'id_mapel' => 12,
                'id_guru' => 13,
                'hari' => 'Selasa',
                'jam_mulai' => '11.00',
                'jam_selesai' => '12.00',
            ],
            [
                'jam_ke' => 6,
                'id_kelas' => 3,
                'id_mapel' => 13,
                'id_guru' => 14,
                'hari' => 'Selasa',
                'jam_mulai' => '12.00',
                'jam_selesai' => '13.00',
            ],
            [
                'jam_ke' => 7,
                'id_kelas' => 3,
                'id_mapel' => 14,
                'id_guru' => 15,
                'hari' => 'Selasa',
                'jam_mulai' => '13.00',
                'jam_selesai' => '14.00',
            ],
            [
                'jam_ke' => 8,
                'id_kelas' => 3,
                'id_mapel' => 15,
                'id_guru' => 16,
                'hari' => 'Selasa',
                'jam_mulai' => '14.00',
                'jam_selesai' => '15.00',
            ],
            [
                'jam_ke' => 1,
                'id_kelas' => 3,
                'id_mapel' => 16,
                'id_guru' => 17,
                'hari' => 'Rabu',
                'jam_mulai' => '07.00',
                'jam_selesai' => '08.00',
            ],
            [
                'jam_ke' => 2,
                'id_kelas' => 3,
                'id_mapel' => 17,
                'id_guru' => 18,
                'hari' => 'Rabu',
                'jam_mulai' => '08.00',
                'jam_selesai' => '09.00',
            ],
            [
                'jam_ke' => 3,
                'id_kelas' => 3,
                'id_mapel' => 18,
                'id_guru' => 19,
                'hari' => 'Rabu',
                'jam_mulai' => '09.00',
                'jam_selesai' => '10.00',
            ],
            [
                'jam_ke' => 4,
                'id_kelas' => 3,
                'id_mapel' => 19,
                'id_guru' => 20,
                'hari' => 'Rabu',
                'jam_mulai' => '10.00',
                'jam_selesai' => '11.00',
            ],
            [
                'jam_ke' => 5,
                'id_kelas' => 3,
                'id_mapel' => 2,
                'id_guru' => 1,
                'hari' => 'Rabu',
                'jam_mulai' => '11.00',
                'jam_selesai' => '12.00',
            ],
            [
                'jam_ke' => 6,
                'id_kelas' => 3,
                'id_mapel' => 3,
                'id_guru' => 2,
                'hari' => 'Rabu',
                'jam_mulai' => '12.00',
                'jam_selesai' => '13.00',
            ],
            [
                'jam_ke' => 7,
                'id_kelas' => 3,
                'id_mapel' => 4,
                'id_guru' => 3,
                'hari' => 'Rabu',
                'jam_mulai' => '13.00',
                'jam_selesai' => '14.00',
            ],
            [
                'jam_ke' => 8,
                'id_kelas' => 3,
                'id_mapel' => 5,
                'id_guru' => 4,
                'hari' => 'Rabu',
                'jam_mulai' => '14.00',
                'jam_selesai' => '15.00',
            ],
            [
                'jam_ke' => 1,
                'id_kelas' => 3,
                'id_mapel' => 6,
                'id_guru' => 5,
                'hari' => 'Kamis',
                'jam_mulai' => '07.00',
                'jam_selesai' => '08.00',
            ],
            [
                'jam_ke' => 2,
                'id_kelas' => 3,
                'id_mapel' => 7,
                'id_guru' => 6,
                'hari' => 'Kamis',
                'jam_mulai' => '08.00',
                'jam_selesai' => '09.00',
            ],
            [
                'jam_ke' => 3,
                'id_kelas' => 3,
                'id_mapel' => 8,
                'id_guru' => 7,
                'hari' => 'Kamis',
                'jam_mulai' => '09.00',
                'jam_selesai' => '10.00',
            ],
            [
                'jam_ke' => 4,
                'id_kelas' => 3,
                'id_mapel' => 9,
                'id_guru' => 8,
                'hari' => 'Kamis',
                'jam_mulai' => '10.00',
                'jam_selesai' => '11.00',
            ],
            [
                'jam_ke' => 5,
                'id_kelas' => 3,
                'id_mapel' => 10,
                'id_guru' => 9,
                'hari' => 'Kamis',
                'jam_mulai' => '11.00',
                'jam_selesai' => '12.00',
            ],
            [
                'jam_ke' => 6,
                'id_kelas' => 3,
                'id_mapel' => 11,
                'id_guru' => 10,
                'hari' => 'Kamis',
                'jam_mulai' => '12.00',
                'jam_selesai' => '13.00',
            ],
            [
                'jam_ke' => 7,
                'id_kelas' => 3,
                'id_mapel' => 12,
                'id_guru' => 11,
                'hari' => 'Kamis',
                'jam_mulai' => '13.00',
                'jam_selesai' => '14.00',
            ],
            [
                'jam_ke' => 8,
                'id_kelas' => 3,
                'id_mapel' => 13,
                'id_guru' => 12,
                'hari' => 'Kamis',
                'jam_mulai' => '14.00',
                'jam_selesai' => '15.00',
            ],
            [
                'jam_ke' => 1,
                'id_kelas' => 3,
                'id_mapel' => 14,
                'id_guru' => 13,
                'hari' => 'Jumat',
                'jam_mulai' => '07.00',
                'jam_selesai' => '08.00',
            ],
            [
                'jam_ke' => 2,
                'id_kelas' => 3,
                'id_mapel' => 15,
                'id_guru' => 14,
                'hari' => 'Jumat',
                'jam_mulai' => '08.00',
                'jam_selesai' => '09.00',
            ],
            [
                'jam_ke' => 3,
                'id_kelas' => 3,
                'id_mapel' => 16,
                'id_guru' => 15,
                'hari' => 'Jumat',
                'jam_mulai' => '09.00',
                'jam_selesai' => '10.00',
            ],
            [
                'jam_ke' => 4,
                'id_kelas' => 3,
                'id_mapel' => 17,
                'id_guru' => 16,
                'hari' => 'Jumat',
                'jam_mulai' => '10.00',
                'jam_selesai' => '11.00',
            ],
            [
                'jam_ke' => 5,
                'id_kelas' => 3,
                'id_mapel' => 18,
                'id_guru' => 17,
                'hari' => 'Jumat',
                'jam_mulai' => '11.00',
                'jam_selesai' => '12.00',
            ],
            [
                'jam_ke' => 6,
                'id_kelas' => 3,
                'id_mapel' => 19,
                'id_guru' => 18,
                'hari' => 'Jumat',
                'jam_mulai' => '12.00',
                'jam_selesai' => '13.00',
            ],
            [
                'jam_ke' => 7,
                'id_kelas' => 3,
                'id_mapel' => 1,
                'id_guru' => 2,
                'hari' => 'Jumat',
                'jam_mulai' => '13.00',
                'jam_selesai' => '14.00',
            ],
            [
                'jam_ke' => 8,
                'id_kelas' => 3,
                'id_mapel' => 2,
                'id_guru' => 3,
                'hari' => 'Jumat',
                'jam_mulai' => '14.00',
                'jam_selesai' => '15.00',
            ],
        ];
        $semester = Semester::where('is_active', 1)->first();
        foreach ($jadwals as $jadwal) {
            JadwalPelajaran::create(
                array_merge(
                    $jadwal,
                    ['semester_id' => $semester->id]
                )
            );
        }
    }
}
